name       : mingw-w64
version    : 6.0.0
release    : 2
source     :
    - https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v6.0.0.tar.bz2 : 805e11101e26d7897fce7d49cbb140d7bac15f3e085a91e0001e80b2adaf48f0
license    :
    - Public-Domain
    - GPL-3.0-or-later
    - ZPL-2.1
component  : programming.devel
summary    :
    - The MinGW-w64 project binaries, runtimes and libraries for 64 bits
    - 32bit: The MinGW-w64 project binaries, runtimes and libraries for 32 bits
description: |
    The mingw-w64 project is a complete runtime environment for gcc to support binaries native to Windows 64-bit and 32-bit operating systems.
homepage   : http://mingw-w64.org/doku.php
strip      : no
patterns   :
    - 32bit:
        - /usr/share/mingw-w64/i686-w64-mingw32/*
builddeps  :
    - mingw-w64
    - mingw-w64-binutils
    - mingw-w64-gcc
    - mingw-w64-32bit
    - mingw-w64-binutils-32bit
    - mingw-w64-gcc-32bit
rundeps    :
    - mingw-w64-binutils
    - 32bit:
        - mingw-w64-binutils-32bit
environment: |
    export CFLAGS="-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT"
    export CXXFLAGS="-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT"
    export LDFLAGS="-Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,--sort-common"
    export PREFIX=/usr/share/mingw-w64
    export PATH=$PATH:$PREFIX/bin
    export TARGET32=i686-w64-mingw32
    export TARGET64=x86_64-w64-mingw32
    unset CC CXX
setup      : |
    _headers_conf() {
        ../mingw-w64-headers/configure \
            --host=$1 \
            --prefix=$PREFIX/$1 \
            --enable-secure-api \
            --enable-sdk=all
    }

    _crt_conf() {
        if [ $1 == $TARGET32 ]; then
            export _crt_cfg_args="--disable-lib64 --enable-lib32"
        elif [ $1 == $TARGET64 ]; then
            export _crt_cfg_args="--disable-lib32 --enable-lib64"
        fi

        # Some empty headers are required for the building process
        export CPPFLAGS=-I$pkgfiles/include
        ../mingw-w64-crt/configure \
            --host=$1 \
            --enable-experimental \
            --enable-wildcard \
            --prefix=$PREFIX/$1 \
            --includedir=$PREFIX/$1/include \
            $_crt_cfg_args
        unset CPPFLAGS
    }

    _winpthreads_conf() {
        ../mingw-w64-libraries/winpthreads/configure \
            --host=$1 \
            --prefix=$PREFIX/$1 \
            --enable-shared \
            --enable-static
    }

    mkdir headdir32 && pushd headdir32
    _headers_conf $TARGET32
    popd
    mkdir headdir64 && pushd headdir64
    _headers_conf $TARGET64
    popd

    mkdir crtdir32 && pushd crtdir32
    _crt_conf $TARGET32
    popd
    mkdir crtdir64 && pushd crtdir64
    _crt_conf $TARGET64
    popd

    mkdir pthrdir32 && pushd pthrdir32
    _winpthreads_conf $TARGET32
    popd
    mkdir pthrdir64 && pushd pthrdir64
    _winpthreads_conf $TARGET64
    popd
build      : |
    %make -C crtdir32
    %make -C crtdir64
    %make -C pthrdir32
    %make -C pthrdir64
install    : |
    %make_install -C headdir32
    %make_install -C headdir64
    %make install-strip -C crtdir32 DESTDIR=$installdir
    %make install-strip -C crtdir64 DESTDIR=$installdir
    %make install-strip -C pthrdir32 DESTDIR=$installdir
    %make install-strip -C pthrdir64 DESTDIR=$installdir
