name       : mingw-w64
version    : 6.0.0
release    : 1
source     :
    - https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v6.0.0.tar.bz2 : 805e11101e26d7897fce7d49cbb140d7bac15f3e085a91e0001e80b2adaf48f0
license    :
    - Public-Domain
    - GPL-3.0-or-later
    - ZPL-2.1
component  : programming.devel
summary    :
    - The MinGW-w64 project binaries, runtimes and libraries for 64 bits
    - 32bit: The MinGW-w64 project binaries, runtimes and libraries for 32 bits
description: |
    The mingw-w64 project is a complete runtime environment for gcc to support binaries native to Windows 64-bit and 32-bit operating systems.
homepage   : http://mingw-w64.org/doku.php
strip      : no
patterns   :
    - 32bit:
        - /usr/share/mingw-w64/i686-w64-mingw32/*
builddeps  :
    - mingw-w64-binutils
    - mingw-w64-gcc
    - mingw-w64-binutils-32bit
    - mingw-w64-gcc-32bit
environment: |
    export TARGET32=i686-w64-mingw32
    export TARGET64=x86_64-w64-mingw32
    export PREFIX=/usr/share/mingw-w64
    export PATH=$PATH:$PREFIX/bin
    unset CC CXX CFLAGS CXXFLAGS LDFLAGS
setup      : |
    _crt_conf() {
        if [ $1 == $TARGET32 ]; then
            export _crt_cfg_args="--disable-lib64 --enable-lib32"
        elif [ $1 == $TARGET64 ]; then
            export _crt_cfg_args="--disable-lib32 --enable-lib64"
        fi

        # Some empty headers are required for the building process
        export CPPFLAGS=-I$pkgfiles/include
        ../mingw-w64-crt/configure \
            --host=$1 \
            --enable-experimental \
            --enable-wildcard \
            --prefix=$PREFIX/$1 \
            $_crt_cfg_args
        unset CPPFLAGS
    }

    mkdir crtdir32 && pushd crtdir32
    _crt_conf $TARGET32
    popd
    mkdir crtdir64 && pushd crtdir64
    _crt_conf $TARGET64
build      : |
    %make -C crtdir32
    %make -C crtdir64
install    : |
    %make install-strip -C crtdir32 DESTDIR=$installdir
    %make install-strip -C crtdir64 DESTDIR=$installdir
