name       : mingw-w64
version    : 8.0.0
release    : 3
source     :
    - https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v8.0.0.tar.bz2 : 44c740ea6ab3924bc3aa169bad11ad3c5766c5c8459e3126d44eabb8735a5762
license    :
    - Public-Domain
    - GPL-3.0-or-later
    - ZPL-2.1
component  : programming.devel
summary    :
    - The MinGW-w64 project binaries, runtimes and libraries for 64 bits
    - 32bit : The MinGW-w64 project binaries, runtimes and libraries for 32 bits
description: |
    The mingw-w64 project is a complete runtime environment for gcc to support binaries native to Windows 64-bit and 32-bit operating systems.
homepage   : http://mingw-w64.org/doku.php
strip      : no
patterns   :
    - 32bit :
        - /usr/share/mingw-w64/i686-w64-mingw32
builddeps  :
    - mingw-w64-gcc-32bit
rundeps    :
    - mingw-w64-binutils
    - 32bit :
        - mingw-w64-binutils-32bit
environment: |
    export CFLAGS="-O3 -mtune=generic -march=x86-64"
    export CXXFLAGS="-O3 -mtune=generic -march=x86-64"
    export PREFIX=/usr/share/mingw-w64
    export PATH=$PATH:$PREFIX/bin
    export TARGET32=i686-w64-mingw32
    export TARGET64=x86_64-w64-mingw32
    unset CC CXX LDFLAGS

    _set_c_flags() {
        export CC=$1-gcc
        export CXX=$1-g++
        export CPPFLAGS=-I$installdir/$PREFIX/$1/include
    }
setup      : |
    _crt_conf() {
        _set_c_flags $1
        if [ $1 == $TARGET32 ]; then
            export _crt_cfg_args="--disable-lib64 --enable-lib32"
        elif [ $1 == $TARGET64 ]; then
            export _crt_cfg_args="--disable-lib32 --enable-lib64"
        fi

        ../mingw-w64-crt/configure \
            --host=$1 \
            --enable-experimental \
            --enable-wildcard \
            --prefix=$PREFIX/$1 \
            --includedir=$PREFIX/$1/include \
            $_crt_cfg_args
    }

    mkdir crtdir32 && pushd crtdir32
    _crt_conf $TARGET32
    popd
    mkdir crtdir64 && pushd crtdir64
    _crt_conf $TARGET64
    popd
build      : |
    %make -C crtdir32
    %make -C crtdir64
install    : |
    %make install-strip -C crtdir32 DESTDIR=$installdir
    %make install-strip -C crtdir64 DESTDIR=$installdir
